import {defineArrayMember, defineField, defineType} from 'sanity'

const CATEGORY_OPTIONS = [
  {title: 'Μόδα', value: 'fashion'},
  {title: 'Εστίαση', value: 'hospitality'},
  {title: 'Κατασκευές', value: 'construction'},
  {title: 'Μέσα ενημέρωσης', value: 'media'},
  {title: 'Αθλητισμός', value: 'sports'},
  {title: 'Τουρισμός', value: 'travel'},
]

export const caseStudyV2 = defineType({
  name: 'caseStudyV2',
  title: 'Έργο (v2)',
  type: 'document',
  fields: [
    defineField({
      name: 'name',
      title: 'Όνομα',
      type: 'string',
      validation: (Rule) => Rule.required(),
    }),
    defineField({
      name: 'slug',
      title: 'Slug',
      type: 'slug',
      options: {source: 'name', maxLength: 96},
      validation: (Rule) => Rule.required(),
    }),
    defineField({
      name: 'kind',
      title: 'Είδος',
      type: 'string',
      initialValue: 'product',
      options: {
        list: [
          {title: 'Δικό μου προϊόν', value: 'product'},
          {title: 'Έργο πελάτη', value: 'client'},
        ],
        layout: 'radio',
      },
    }),
    defineField({
      name: 'asProjectManager',
      title: 'Συμμετοχή ως Project Manager',
      type: 'boolean',
      initialValue: false,
      description: 'Εμφανίζεται στο φίλτρο «Έργα πελατών που συμμετείχα ως Project Manager».',
      hidden: ({parent}) => parent?.kind !== 'client',
    }),
    defineField({
      name: 'tag',
      title: 'Ετικέτα',
      type: 'string',
      description: 'Π.χ. "Δικό μου SaaS".',
    }),
    defineField({name: 'sector', title: 'Κλάδος', type: 'string'}),
    defineField({
      name: 'category',
      title: 'Κατηγορία φίλτρου',
      type: 'string',
      options: {list: CATEGORY_OPTIONS},
    }),
    defineField({
      name: 'liveUrl',
      title: 'Live URL',
      type: 'url',
      description: 'Σύνδεσμος «Δες το live site».',
    }),
    defineField({name: 'platform', title: 'Πλατφόρμα', type: 'string'}),
    defineField({name: 'cms', title: 'CMS', type: 'string'}),
    defineField({
      name: 'headline',
      title: 'Τίτλος',
      type: 'text',
      rows: 2,
      validation: (Rule) => Rule.required(),
    }),
    defineField({name: 'short', title: 'Σύντομη περιγραφή', type: 'text', rows: 2}),
    defineField({name: 'role', title: 'Ρόλος', type: 'string'}),
    defineField({name: 'duration', title: 'Διάρκεια', type: 'string'}),
    defineField({
      name: 'stack',
      title: 'Stack',
      type: 'array',
      of: [defineArrayMember({type: 'string'})],
    }),
    defineField({
      name: 'highlights',
      title: 'Τι περιλαμβάνει',
      type: 'array',
      of: [defineArrayMember({type: 'string'})],
    }),
    defineField({
      name: 'deliveredVia',
      title: 'Παραδόθηκε μέσω',
      type: 'string',
      description: 'Π.χ. ftiaxesite.gr',
    }),
    defineField({name: 'problem', title: 'Το πρόβλημα', type: 'text', rows: 6}),
    defineField({name: 'approach', title: 'Η προσέγγιση', type: 'text', rows: 6}),
    defineField({name: 'solution', title: 'Η λύση', type: 'text', rows: 6}),
    defineField({
      name: 'results',
      title: 'Τι άλλαξε',
      type: 'array',
      of: [defineArrayMember({type: 'resultStat'})],
    }),
    defineField({
      name: 'artKey',
      title: 'Γραφικό',
      type: 'string',
      initialValue: 'kollekta',
      options: {
        list: [
          {title: 'Kollekta', value: 'kollekta'},
          {title: 'Site', value: 'site'},
          {title: 'Audit', value: 'audit'},
          {title: 'ERP ↔ e-shop', value: 'erp'},
          {title: 'XML feed / Attiki', value: 'feed'},
          {title: 'B2B', value: 'b2b'},
        ],
      },
    }),
    defineField({
      name: 'coverImage',
      title: 'Εικόνα εξωφύλλου',
      type: 'image',
      description: 'Αν οριστεί, αντικαθιστά το γραφικό.',
      options: {hotspot: true},
      fields: [defineField({name: 'alt', title: 'Alt', type: 'string'})],
    }),
    defineField({
      name: 'gallery',
      title: 'Gallery',
      type: 'array',
      of: [
        defineArrayMember({
          type: 'image',
          options: {hotspot: true},
          fields: [defineField({name: 'alt', title: 'Alt', type: 'string'})],
        }),
      ],
    }),
    defineField({
      name: 'featured',
      title: 'Επιλεγμένο (home)',
      type: 'boolean',
      initialValue: false,
      description: 'Δεν αλλάζει αυτόματα το home. Χρησιμοποιείται ως σήμανση.',
    }),
    defineField({
      name: 'isPlaceholder',
      title: 'Placeholder',
      type: 'boolean',
      initialValue: false,
    }),
    defineField({
      name: 'reviewNote',
      title: 'Σημείωση (μόνο Studio)',
      type: 'text',
      rows: 3,
      description: 'Εσωτερική. Δεν εμφανίζεται στο site.',
    }),
    defineField({
      name: 'order',
      title: 'Σειρά',
      type: 'number',
      validation: (Rule) => Rule.required(),
    }),
    defineField({name: 'seo', title: 'SEO', type: 'seo'}),
  ],
  orderings: [{title: 'Σειρά', name: 'orderAsc', by: [{field: 'order', direction: 'asc'}]}],
  preview: {
    select: {title: 'name', subtitle: 'sector', media: 'coverImage'},
  },
})
