import {defineArrayMember, defineField, defineType} from 'sanity'

export const homePage = defineType({
  name: 'homePage',
  title: 'Αρχική',
  type: 'document',
  groups: [
    {name: 'hero', title: 'Hero', default: true},
    {name: 'story', title: 'Μανιφέστο & αξίες'},
    {name: 'services', title: 'Υπηρεσίες & agencies'},
    {name: 'process', title: 'Διαδικασία & σύγκριση'},
    {name: 'proof', title: 'Έργα, κριτικές, FAQ'},
    {name: 'seo', title: 'SEO'},
  ],
  fields: [
    defineField({
      name: 'hero',
      title: 'Hero',
      type: 'object',
      group: 'hero',
      fields: [
        defineField({name: 'eyebrow', title: 'Eyebrow', type: 'string'}),
        defineField({
          name: 'headingLines',
          title: 'Γραμμές τίτλου',
          type: 'array',
          of: [defineArrayMember({type: 'headingLine'})],
        }),
        defineField({name: 'swapPrefix', title: 'Κείμενο πριν τη λέξη', type: 'string'}),
        defineField({
          name: 'swapWords',
          title: 'Λέξεις που εναλλάσσονται',
          type: 'array',
          of: [defineArrayMember({type: 'string'})],
        }),
        defineField({name: 'swapSuffix', title: 'Κείμενο μετά τη λέξη', type: 'text', rows: 3}),
        defineField({
          name: 'ctas',
          title: 'Κουμπιά',
          type: 'array',
          of: [defineArrayMember({type: 'cta'})],
        }),
        defineField({
          name: 'facts',
          title: 'Αριθμοί',
          type: 'array',
          of: [defineArrayMember({type: 'fact'})],
          validation: (Rule) => Rule.max(4),
        }),
      ],
    }),
    defineField({
      name: 'marqueeTop',
      title: 'Marquee (πάνω)',
      type: 'array',
      of: [defineArrayMember({type: 'string'})],
      group: 'hero',
    }),
    defineField({
      name: 'marqueeBottom',
      title: 'Marquee (κάτω)',
      type: 'array',
      of: [defineArrayMember({type: 'string'})],
      group: 'hero',
    }),
    defineField({
      name: 'manifesto',
      title: 'Μανιφέστο',
      type: 'object',
      group: 'story',
      fields: [
        defineField({name: 'eyebrow', title: 'Eyebrow', type: 'string'}),
        defineField({name: 'text', title: 'Κείμενο', type: 'richTextV2'}),
      ],
    }),
    defineField({
      name: 'values',
      title: 'Αξίες',
      type: 'array',
      of: [defineArrayMember({type: 'valueCard'})],
      group: 'story',
      validation: (Rule) => Rule.max(3),
    }),
    defineField({
      name: 'servicesSection',
      title: 'Ενότητα υπηρεσιών',
      type: 'object',
      group: 'services',
      fields: [
        defineField({name: 'eyebrow', title: 'Eyebrow', type: 'string'}),
        defineField({name: 'heading', title: 'Τίτλος', type: 'text', rows: 2}),
        defineField({name: 'intro', title: 'Εισαγωγή', type: 'text', rows: 3}),
        defineField({
          name: 'services',
          title: 'Υπηρεσίες',
          type: 'array',
          of: [defineArrayMember({type: 'reference', to: [{type: 'serviceV2'}]})],
        }),
      ],
    }),
    defineField({
      name: 'partnerBand',
      title: 'Ενότητα agencies',
      type: 'object',
      group: 'services',
      fields: [
        defineField({name: 'eyebrow', title: 'Eyebrow', type: 'string'}),
        defineField({name: 'heading', title: 'Τίτλος', type: 'string'}),
        defineField({
          name: 'headingHighlight',
          title: 'Τίτλος σε marigold',
          type: 'string',
          description: 'Το κομμάτι του τίτλου που τονίζεται.',
        }),
        defineField({name: 'text', title: 'Κείμενο', type: 'text', rows: 4}),
        defineField({
          name: 'bullets',
          title: 'Λίστα',
          type: 'array',
          of: [defineArrayMember({type: 'bulletItem'})],
        }),
        defineField({
          name: 'ctas',
          title: 'Κουμπιά',
          type: 'array',
          of: [defineArrayMember({type: 'cta'})],
        }),
      ],
    }),
    defineField({
      name: 'processSection',
      title: 'Ενότητα διαδικασίας',
      type: 'object',
      group: 'process',
      fields: [
        defineField({name: 'eyebrow', title: 'Eyebrow', type: 'string'}),
        defineField({name: 'heading', title: 'Τίτλος', type: 'text', rows: 2}),
        defineField({name: 'cta', title: 'Κουμπί', type: 'cta'}),
      ],
    }),
    defineField({
      name: 'compareSection',
      title: 'Ενότητα σύγκρισης',
      type: 'object',
      group: 'process',
      fields: [
        defineField({name: 'eyebrow', title: 'Eyebrow', type: 'string'}),
        defineField({name: 'heading', title: 'Τίτλος', type: 'text', rows: 2}),
        defineField({name: 'intro', title: 'Εισαγωγή', type: 'text', rows: 2}),
        defineField({name: 'rowsTitle', title: 'Τίτλος πίνακα', type: 'string'}),
        defineField({name: 'leftLabel', title: 'Αριστερή ετικέτα', type: 'string'}),
        defineField({name: 'rightLabel', title: 'Δεξιά ετικέτα', type: 'string'}),
        defineField({
          name: 'rows',
          title: 'Γραμμές',
          type: 'array',
          of: [defineArrayMember({type: 'compareRow'})],
        }),
      ],
    }),
    defineField({
      name: 'featuredCasesSection',
      title: 'Επιλεγμένα έργα',
      type: 'object',
      group: 'proof',
      fields: [
        defineField({name: 'eyebrow', title: 'Eyebrow', type: 'string'}),
        defineField({name: 'heading', title: 'Τίτλος', type: 'text', rows: 2}),
        defineField({name: 'intro', title: 'Εισαγωγή', type: 'text', rows: 2}),
        defineField({name: 'ctaLabel', title: 'Κείμενο κουμπιού', type: 'string'}),
      ],
    }),
    defineField({
      name: 'featuredCases',
      title: 'Έργα (το πρώτο είναι wide)',
      type: 'array',
      of: [defineArrayMember({type: 'reference', to: [{type: 'caseStudyV2'}]})],
      group: 'proof',
    }),
    defineField({
      name: 'testimonialSection',
      title: 'Κριτική',
      type: 'object',
      group: 'proof',
      fields: [
        defineField({name: 'eyebrow', title: 'Eyebrow', type: 'string'}),
        defineField({
          name: 'testimonial',
          title: 'Κριτική',
          type: 'reference',
          to: [{type: 'testimonialV2'}],
          description: 'Αν λείπει ή δεν είναι εγκεκριμένη, εμφανίζεται το placeholder.',
        }),
        defineField({
          name: 'placeholderQuote',
          title: 'Placeholder κριτική',
          type: 'text',
          rows: 3,
        }),
        defineField({
          name: 'placeholderAttribution',
          title: 'Placeholder υπογραφή',
          type: 'string',
        }),
      ],
    }),
    defineField({
      name: 'faq',
      title: 'Συχνές ερωτήσεις',
      type: 'object',
      group: 'proof',
      fields: [
        defineField({name: 'eyebrow', title: 'Eyebrow', type: 'string'}),
        defineField({name: 'heading', title: 'Τίτλος', type: 'string'}),
        defineField({
          name: 'items',
          title: 'Ερωτήσεις',
          type: 'array',
          of: [defineArrayMember({type: 'faqItem'})],
        }),
      ],
    }),
    defineField({name: 'bigCta', title: 'Μεγάλο CTA', type: 'bigCta', group: 'proof'}),
    defineField({name: 'seo', title: 'SEO', type: 'seo', group: 'seo'}),
  ],
  preview: {prepare: () => ({title: 'Αρχική'})},
})
