import {defineField, defineType} from 'sanity'

export const aboutPage = defineType({
  name: 'aboutPage',
  title: 'About Page',
  type: 'document',
  groups: [
    {name: 'hero', title: 'Hero', default: true},
    {name: 'philosophy', title: 'Philosophy'},
    {name: 'story', title: 'Story & Timeline'},
    {name: 'workStyle', title: 'Work Style'},
    {name: 'stats', title: 'Stats'},
    {name: 'comparison', title: 'Comparison'},
    {name: 'cta', title: 'CTA'},
    {name: 'media', title: 'Media'},
    {name: 'seo', title: 'SEO'},
  ],
  fields: [
    defineField({
      name: 'headline',
      title: 'Name (H1)',
      type: 'string',
      group: 'hero',
      initialValue: 'Dimitris Geronikolos',
      validation: (Rule) => Rule.required(),
    }),
    defineField({
      name: 'subheadline',
      title: 'Role (H2)',
      type: 'localeString',
      group: 'hero',
    }),
    defineField({
      name: 'intro',
      title: 'Intro Paragraph',
      type: 'localeText',
      group: 'hero',
      rows: 3,
    }),
    defineField({
      name: 'heroBadgeValue',
      title: 'Photo Badge Value',
      type: 'string',
      group: 'hero',
      initialValue: '15+',
    }),
    defineField({
      name: 'heroBadgeLabel',
      title: 'Photo Badge Label',
      type: 'localeString',
      group: 'hero',
    }),
    defineField({
      name: 'primaryCtaText',
      title: 'Primary CTA Text',
      type: 'localeString',
      group: 'hero',
    }),
    defineField({
      name: 'primaryCtaLink',
      title: 'Primary CTA Link',
      type: 'string',
      group: 'hero',
      initialValue: '/#cases',
    }),
    defineField({
      name: 'secondaryCtaText',
      title: 'Secondary CTA Text',
      type: 'localeString',
      group: 'hero',
    }),
    defineField({
      name: 'secondaryCtaLink',
      title: 'Secondary CTA Link',
      type: 'string',
      group: 'hero',
      initialValue: '#',
    }),
    defineField({
      name: 'photo',
      title: 'Portrait Photo',
      type: 'image',
      group: 'media',
      options: {hotspot: true},
      fields: [defineField({name: 'alt', title: 'Alt Text', type: 'localeString'})],
    }),
    defineField({
      name: 'photoUrl',
      title: 'Photo URL (fallback)',
      type: 'url',
      group: 'media',
    }),
    defineField({
      name: 'philosophyHeadline',
      title: 'Philosophy Headline',
      type: 'localeString',
      group: 'philosophy',
    }),
    defineField({
      name: 'philosophyHighlight',
      title: 'Philosophy Highlight',
      type: 'localeString',
      group: 'philosophy',
    }),
    defineField({
      name: 'philosophyParagraphs',
      title: 'Philosophy Paragraphs',
      type: 'array',
      group: 'philosophy',
      of: [{type: 'localeText'}],
    }),
    defineField({
      name: 'storySections',
      title: 'Story Sections',
      type: 'array',
      group: 'story',
      of: [{type: 'aboutStorySection'}],
    }),
    defineField({
      name: 'timeline',
      title: 'Career Timeline',
      type: 'array',
      group: 'story',
      of: [{type: 'aboutTimelineItem'}],
    }),
    defineField({
      name: 'workStyleHeadline',
      title: 'Work Style Headline',
      type: 'localeString',
      group: 'workStyle',
    }),
    defineField({
      name: 'workStyleSubheadline',
      title: 'Work Style Subheadline',
      type: 'localeText',
      group: 'workStyle',
      rows: 2,
    }),
    defineField({
      name: 'approach',
      title: 'Work Style Cards',
      type: 'array',
      group: 'workStyle',
      of: [{type: 'approachPoint'}],
    }),
    defineField({
      name: 'stats',
      title: 'Stats Row',
      type: 'array',
      group: 'stats',
      of: [{type: 'aboutStat'}],
      validation: (Rule) => Rule.max(4),
    }),
    defineField({
      name: 'comparisonHeadline',
      title: 'Comparison Section Headline',
      type: 'localeString',
      group: 'comparison',
    }),
    defineField({
      name: 'comparisons',
      title: 'Comparison Blocks',
      type: 'array',
      group: 'comparison',
      of: [{type: 'aboutComparison'}],
    }),
    defineField({
      name: 'testimonialsHeadline',
      title: 'Testimonials Headline',
      type: 'localeString',
      group: 'cta',
    }),
    defineField({
      name: 'featuredTestimonials',
      title: 'Featured Testimonials',
      type: 'array',
      group: 'cta',
      of: [{type: 'reference', to: [{type: 'testimonial'}]}],
      description: 'Leave empty to show the first 3 testimonials',
    }),
    defineField({
      name: 'ctaHeadline',
      title: 'CTA Headline',
      type: 'localeString',
      group: 'cta',
    }),
    defineField({
      name: 'ctaDescription',
      title: 'CTA Description',
      type: 'localeText',
      group: 'cta',
      rows: 3,
    }),
    defineField({
      name: 'ctaText',
      title: 'CTA Button Text',
      type: 'localeString',
      group: 'cta',
    }),
    defineField({
      name: 'ctaLink',
      title: 'CTA Link',
      type: 'string',
      group: 'cta',
      initialValue: '/#contact',
    }),
    defineField({
      name: 'seo',
      title: 'SEO',
      type: 'object',
      group: 'seo',
      fields: [
        defineField({name: 'metaTitle', title: 'Meta Title', type: 'localeString'}),
        defineField({name: 'metaDescription', title: 'Meta Description', type: 'localeText', rows: 3}),
      ],
    }),
  ],
  preview: {
    select: {title: 'headline', subtitle: 'subheadline.el'},
  },
})
